name: proyectofinal
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  firebase_auth: ^5.1.4
  google_sign_in: ^5.4.2
  cloud_firestore: ^5.0.0
  firebase_remote_config: ^5.0.4
  firebase_analytics: ^11.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1
  hive: ^2.0.4
  hive_flutter: ^1.1.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/mask_group_3_x2.svg

